-- MySQL Script generated by MySQL Workbench
-- 06/01/15 16:13:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql378796` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sql378796` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql378796`.`Reservas` (
  `IDReserva` INT NOT NULL,
  `Cedula` INT NULL,
  `Restaurante` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Hora` DATETIME NULL,
  `Lugar` VARCHAR(45) NULL,
  `Mesa` VARCHAR(45) NULL,
  PRIMARY KEY (`IDReserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql378796`.`Restaurantes` (
  `IDRestaurante` INT NOT NULL,
  `Nombre Restaurante` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Capacidad Restaurante` INT NULL,
  `Hora Inicio` DATETIME NULL,
  `Hora Fin` DATETIME NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`IDRestaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql378796`.`Cliente` (
  `Cedula` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql378796`.`Capacidad` (
  `IDRestaurante` INT NOT NULL,
  `Mesa` VARCHAR(45) NULL,
  `Capacidad` INT NULL,
  PRIMARY KEY (`IDRestaurante`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
